analytics-disable: true
attribute-author: false
attribute-co-authored-by: false
attribute-commit-message-author: false
attribute-commit-message-committer: false
attribute-committer: false
auto-commits: false
auto-lint: false
editor: vim
gitignore: false
vim: true
